### ISSUE TITLE
Bad performance

### ISSUE THREAD

**Issue by fklingler** [jamesdixon/node-ember-cli-deploy-azure-tables#2]
Hello,

Now that I use this library with a real server, it seems that it has really bad performance.
I have a response time of 500-600ms with this following code, when my API responds in less than 20ms every time:

```
    app.use('/*', require('node-ember-cli-deploy-azure-tables')({
      accountName: process.env.EMBER_DEPLOY_AZURE_ACCOUNT,
      accessKey: process.env.EMBER_DEPLOY_AZURE_KEY,
    }, 'appname'));
```

Do you have comparable response time? Is it normal for you?

**Comment by jamesdixon** [comment]
Hi @fklingler - sorry to hear you're having issues with performance. I'm actually no longer using Azure Tables so I haven't used the library in some time. Unfortunately, I don't have the time to investigate the issue. 

That said, the code is fairly trivial and doesn't do a whole lot -- the heavy lifting is handled by the `azure-storage` library. Three suggestions:
1. Check the [azure-storage](https://github.com/Azure/azure-storage-node) repo to see if there might be an existing issue that effects the performance of the library.
2. Write a simple script that interacts with the `azure-storage` library directly and see if you still encounter the same results.
3. If no to both of the above, I'd be more than willing to accept a PR if you are able to track down the issue with the library and apply a fix.

Sorry I can't be of more help at the moment.

Best,
James

**Comment by fklingler** [comment]
Thanks for these trails. I will look into that and come back to you on this issue if I find anything.

**Comment by fklingler** [comment]
I created an issue on the `azure-storage` repo: https://github.com/Azure/azure-storage-node/issues/95, as this was indeed linked to azure and not at all to this project.

This is currently not really usable in production I think, with about 500ms to render the index. I switched to using `ember-cli-deploy-redis` (only for the index, I use azure-blob for the assets which is still great) with `node-ember-cli-deploy-redis`, and I now have only 2ms for the index rendering!!

**Comment by jamesdixon** [comment]
Glad you were able to discover the issue! I'm going to close since it's unrelated to the library.
